---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ako
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  url: https://projects.registry.vmware.com/chartrepo/ako

